name: React build

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: lynn-test-deploy
  PROJECT_NAME: geha-sajang

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
        # node modules 캐싱
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Create zip
        run: zip -qq -r ./build-fe.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://$S3_BUCKET_NAME/build-fe.zip
      
      - name: CD
        run: cd /home/runner/.npm/_logs/
        if: failure()

      - name: ll
        run: ll
        if: failure()

      - name: Upload log to S3
        run: aws s3 cp --recursive --region ap-northeast-2 /home/runner/.npm/_logs/*.log s3://$S3_BUCKET_NAME/error/front
        if: failure()
        
