name: React build

on:
  workflow_dispatch:

env:
  S3_BUCKET_NAME: lynn-test-deploy
  PROJECT_NAME: geha-sajang

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
            
      - name: Pring node veresion
        run: node --version

      - name: Install Dependencies
        run: npm install

      - name: Install axios
        run: npm install --save axios

      - name: Build
        run: npm run build

      # - name: Create zip
      #   run: zip -qq -r ./build-fe.zip .

      # - name: Upload to S3
      #   run: aws s3 cp --region ap-northeast-2 ./build-fe.zip s3://$S3_BUCKET_NAME/build-fe.zip
   
      - name: Upload dist/ to S3
        run: aws s3 cp --recursive --region ap-northeast-2 ./dist/* s3://$S3_BUCKET_NAME/front/

      - name: Upload public/ to S3
        run: aws s3 cp --recursive --region ap-northeast-2 ./public/favicon.ico s3://$S3_BUCKET_NAME/front/public

      - name: log ls
        run: ls /home/runner/.npm/_logs/
        if: failure()

      - name: ls
        run: ls
        if: failure()

      - name: Upload log to S3
        run: aws s3 cp --region ap-northeast-2 /home/runner/.npm/_logs/ s3://$S3_BUCKET_NAME/error/front --recursive
        if: failure()
        
